openapi: 3.1.0
info:
  title: Google Books About User Calendars API
  description: API for retrieving Bookshelf and Volume resources from Google Books
  version: 1.0.0
  contact:
    name: Google Books API
    url: https://developers.google.com/books
servers:
- url: https://www.googleapis.com/books/v1
  description: Google Books API v1
tags:
- name: User Calendars
  description: Operations related to Usersmecalendarlist
paths:
  /users/me/calendarList/{calendarId}:
    get:
      tags:
      - User Calendars
      summary: Google Get Calendar List
      description: Returns a calendar from the user's calendar list.
      operationId: googleGetcalendarlist
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersMeCalendarListGetResponse'
              examples:
                UsersMeCalendarListGetResponseExample:
                  $ref: '#/components/examples/UsersMeCalendarListGetResponseExample'
      x-api-evangelist-certified: '2025-07-20'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersMeCalendarListGetResponseExample
    put:
      tags:
      - User Calendars
      summary: Google Update Calendar List
      description: Updates an existing calendar on the user's calendar list.
      operationId: googleUpdatecalendarlist
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersMeCalendarListPutRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersMeCalendarListPutResponse'
              examples:
                UsersMeCalendarListPutResponseExample:
                  $ref: '#/components/examples/UsersMeCalendarListPutResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersMeCalendarListPutResponseExample
    patch:
      tags:
      - User Calendars
      summary: Google Patch Calendar List
      description: Updates an existing calendar on the user's calendar list. This method supports patch semantics.
      operationId: googlePatchcalendarlist
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersMeCalendarListPatchRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersMeCalendarListPatchResponse'
              examples:
                UsersMeCalendarListPatchResponseExample:
                  $ref: '#/components/examples/UsersMeCalendarListPatchResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersMeCalendarListPatchResponseExample
    delete:
      tags:
      - User Calendars
      summary: Google Remove Calendar On List
      description: Removes a calendar from the user's calendar list.
      operationId: googleRemovecalendaronlist
      parameters:
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      responses:
        '204':
          description: No Content
          headers:
            Content-Type:
              schema:
                type: string
                example: text/plain
          content:
            text/plain:
              schema:
                type: string
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
  /users/me/calendarList:
    post:
      tags:
      - User Calendars
      summary: Google Insert Calendar On List
      description: Inserts an existing calendar into the user's calendar list.
      operationId: googleInsertcalendaronlist
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersMeCalendarListPostRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersMeCalendarListPostResponse'
              examples:
                UsersMeCalendarListPostResponseExample:
                  $ref: '#/components/examples/UsersMeCalendarListPostResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersMeCalendarListPostResponseExample
  /users/{userId}/calendarList:
    get:
      tags:
      - User Calendars
      summary: Google List Calendars
      description: Returns the calendars on the user's calendar list.
      operationId: googleListcalendars
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: (Required)
        example: '{{userId}}'
      - in: header
        name: Authorization
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersCalendarListGetResponse'
              examples:
                UsersCalendarListGetResponseExample:
                  $ref: '#/components/examples/UsersCalendarListGetResponseExample'
      x-api-evangelist-certified: '2025-07-20'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersCalendarListGetResponseExample
  /users/me/calendarList/watch:
    post:
      tags:
      - User Calendars
      summary: Google Watch Calendar List
      description: Watch for changes to CalendarList resources.
      operationId: googleWatchcalendarlist
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeCalendarListWatchPostRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeCalendarListWatchPostResponse'
              examples:
                MeCalendarListWatchPostResponseExample:
                  $ref: '#/components/examples/MeCalendarListWatchPostResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: MeCalendarListWatchPostResponseExample
components:
  schemas:
    UsersMeCalendarListPatchResponseNotificationSettings:
      description: UsersMeCalendarListPatchResponseNotificationSettings schema
      type: object
      properties:
        notifications:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              type:
                type: string
    UsersCalendarListGetResponse:
      description: UsersCalendarListGetResponse schema
      type: object
      properties:
        etag:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              accessRole:
                type: string
              backgroundColor:
                type: string
              colorId:
                type: string
              conferenceProperties:
                type: object
                properties:
                  allowedConferenceSolutionTypes:
                    type: array
                    items:
                      type: string
              defaultReminders:
                type: array
                items:
                  type: object
                  properties:
                    method:
                      type: string
                    minutes:
                      type: integer
              deleted:
                type: string
              description:
                type: string
              etag:
                type: string
              foregroundColor:
                type: string
              hidden:
                type: string
              id:
                type: string
              kind:
                type: string
              location:
                type: string
              notificationSettings:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        method:
                          type: string
                        type:
                          type: string
              primary:
                type: string
              selected:
                type: string
              summary:
                type: string
              summaryOverride:
                type: string
              timeZone:
                type: string
        kind:
          type: string
        nextPageToken:
          type: string
        nextSyncToken:
          type: string
    UsersMeCalendarListGetResponse:
      description: UsersMeCalendarListGetResponse schema
      type: object
      properties:
        accessRole:
          type: string
        backgroundColor:
          type: string
        colorId:
          type: string
        conferenceProperties:
          $ref: '#/components/schemas/UsersMeCalendarListGetResponseConferenceProperties'
        defaultReminders:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              minutes:
                type: integer
        deleted:
          type: string
        description:
          type: string
        etag:
          type: string
        foregroundColor:
          type: string
        hidden:
          type: string
        id:
          type: string
        kind:
          type: string
        location:
          type: string
        notificationSettings:
          $ref: '#/components/schemas/UsersMeCalendarListGetResponseNotificationSettings'
        primary:
          type: string
        selected:
          type: string
        summary:
          type: string
        summaryOverride:
          type: string
        timeZone:
          type: string
    MeCalendarListWatchPostResponseParams:
      description: MeCalendarListWatchPostResponseParams schema
      type: object
      properties:
        reprehenderit5c:
          type: string
        sint_b:
          type: string
    UsersMeCalendarListPutResponse:
      description: UsersMeCalendarListPutResponse schema
      type: object
      properties:
        accessRole:
          type: string
        backgroundColor:
          type: string
        colorId:
          type: string
        conferenceProperties:
          $ref: '#/components/schemas/UsersMeCalendarListPutResponseConferenceProperties'
        defaultReminders:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              minutes:
                type: integer
        deleted:
          type: string
        description:
          type: string
        etag:
          type: string
        foregroundColor:
          type: string
        hidden:
          type: string
        id:
          type: string
        kind:
          type: string
        location:
          type: string
        notificationSettings:
          $ref: '#/components/schemas/UsersMeCalendarListPutResponseNotificationSettings'
        primary:
          type: string
        selected:
          type: string
        summary:
          type: string
        summaryOverride:
          type: string
        timeZone:
          type: string
    UsersMeCalendarListPostResponseConferenceProperties:
      description: UsersMeCalendarListPostResponseConferenceProperties schema
      type: object
      properties:
        allowedConferenceSolutionTypes:
          type: array
          items:
            type: string
    UsersMeCalendarListPutResponseNotificationSettings:
      description: UsersMeCalendarListPutResponseNotificationSettings schema
      type: object
      properties:
        notifications:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              type:
                type: string
    MeCalendarListWatchPostRequest:
      description: MeCalendarListWatchPostRequest schema
      type: object
      example:
        address: incididunt sed consequat
        expiration: velit ad aliq
        id: velit eiusmod
        kind: api#channel
        params:
          reprehenderit5c: non
          sint_b: cupidatat do
        payload: false
        resourceId: aute
        resourceUri: fugiat consequat
        token: ullamco officia in
        type: ex eiusmod adipisicing mollit
    UsersMeCalendarListPatchResponse:
      description: UsersMeCalendarListPatchResponse schema
      type: object
      properties:
        accessRole:
          type: string
        backgroundColor:
          type: string
        colorId:
          type: string
        conferenceProperties:
          $ref: '#/components/schemas/UsersMeCalendarListPatchResponseConferenceProperties'
        defaultReminders:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              minutes:
                type: integer
        deleted:
          type: string
        description:
          type: string
        etag:
          type: string
        foregroundColor:
          type: string
        hidden:
          type: string
        id:
          type: string
        kind:
          type: string
        location:
          type: string
        notificationSettings:
          $ref: '#/components/schemas/UsersMeCalendarListPatchResponseNotificationSettings'
        primary:
          type: string
        selected:
          type: string
        summary:
          type: string
        summaryOverride:
          type: string
        timeZone:
          type: string
    UsersMeCalendarListPutRequest:
      description: UsersMeCalendarListPutRequest schema
      type: object
      example:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
    UsersMeCalendarListPostResponse:
      description: UsersMeCalendarListPostResponse schema
      type: object
      properties:
        accessRole:
          type: string
        backgroundColor:
          type: string
        colorId:
          type: string
        conferenceProperties:
          $ref: '#/components/schemas/UsersMeCalendarListPostResponseConferenceProperties'
        defaultReminders:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              minutes:
                type: integer
        deleted:
          type: string
        description:
          type: string
        etag:
          type: string
        foregroundColor:
          type: string
        hidden:
          type: string
        id:
          type: string
        kind:
          type: string
        location:
          type: string
        notificationSettings:
          $ref: '#/components/schemas/UsersMeCalendarListPostResponseNotificationSettings'
        primary:
          type: string
        selected:
          type: string
        summary:
          type: string
        summaryOverride:
          type: string
        timeZone:
          type: string
    UsersMeCalendarListPatchRequest:
      description: UsersMeCalendarListPatchRequest schema
      type: object
      example:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
    MeCalendarListWatchPostResponse:
      description: MeCalendarListWatchPostResponse schema
      type: object
      properties:
        address:
          type: string
        expiration:
          type: string
        id:
          type: string
        kind:
          type: string
        params:
          $ref: '#/components/schemas/MeCalendarListWatchPostResponseParams'
        payload:
          type: boolean
        resourceId:
          type: string
        resourceUri:
          type: string
        token:
          type: string
        type:
          type: string
    UsersMeCalendarListGetResponseNotificationSettings:
      description: UsersMeCalendarListGetResponseNotificationSettings schema
      type: object
      properties:
        notifications:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              type:
                type: string
    UsersMeCalendarListGetResponseConferenceProperties:
      description: UsersMeCalendarListGetResponseConferenceProperties schema
      type: object
      properties:
        allowedConferenceSolutionTypes:
          type: array
          items:
            type: string
    UsersMeCalendarListPatchResponseConferenceProperties:
      description: UsersMeCalendarListPatchResponseConferenceProperties schema
      type: object
      properties:
        allowedConferenceSolutionTypes:
          type: array
          items:
            type: string
    UsersMeCalendarListPostResponseNotificationSettings:
      description: UsersMeCalendarListPostResponseNotificationSettings schema
      type: object
      properties:
        notifications:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
              type:
                type: string
    UsersMeCalendarListPutResponseConferenceProperties:
      description: UsersMeCalendarListPutResponseConferenceProperties schema
      type: object
      properties:
        allowedConferenceSolutionTypes:
          type: array
          items:
            type: string
    UsersMeCalendarListPostRequest:
      description: UsersMeCalendarListPostRequest schema
      type: object
      example:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
  examples:
    MeCalendarListWatchPostResponseExample:
      summary: Successful 200 response
      value:
        address: incididunt sed consequat
        expiration: velit ad aliq
        id: velit eiusmod
        kind: api#channel
        params:
          reprehenderit5c: non
          sint_b: cupidatat do
        payload: false
        resourceId: aute
        resourceUri: fugiat consequat
        token: ullamco officia in
        type: ex eiusmod adipisicing mollit
    UsersMeCalendarListPostResponseExample:
      summary: Successful 200 response
      value:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
    UsersMeCalendarListGetResponseExample:
      summary: Successful 200 response
      value:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
    UsersMeCalendarListPatchResponseExample:
      summary: Successful 200 response
      value:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
    UsersCalendarListGetResponseExample:
      summary: Successful 200 response
      value:
        etag: qui labore aliqua in
        items:
        - accessRole: qui incididunt do Excepteur
          backgroundColor: ad esse nulla labore adipisicing
          colorId: ipsum
          conferenceProperties:
            allowedConferenceSolutionTypes:
            - adipisici
            - Duis of
          defaultReminders:
          - method: id cupidatat
            minutes: -16296761
          - method: magna mollit proident
            minutes: -16227132
          deleted: 'false'
          description: cupidatat Excepteur
          etag: 'ea '
          foregroundColor: amet enim velit in
          hidden: 'false'
          id: sunt ad ipsum dolore
          kind: calendar#calendarListEntry
          location: deserunt ullamco proident occaecat id
          notificationSettings:
            notifications:
            - method: aliquip
              type: Lorem reprehenderit
            - method: pariatur incididunt
              type: anim consectetur deserunt
          primary: 'false'
          selected: 'false'
          summary: qui
          summaryOverride: velit id eiusmod minim amet
          timeZone: nisi Ut cillum sunt sit
        - accessRole: ea dolor ex sunt ut
          backgroundColor: dolore enim officia amet
          colorId: laborum amet nostrud ipsum deserunt
          conferenceProperties:
            allowedConferenceSolutionTypes:
            - anim consequat
            - dolor Ut ut
          defaultReminders:
          - method: sit qui
            minutes: 60974334
          - method: in culpa
            minutes: 48454696
          deleted: 'false'
          description: eiusmod do minim
          etag: adipisicing ut laborum ea
          foregroundColor: ipsum cillum
          hidden: 'false'
          id: quis Excepteur deserunt
          kind: calendar#calendarListEntry
          location: consequat Excepteur dolor
          notificationSettings:
            notifications:
            - method: nostrud aliquip non
              type: dolor laboris
            - method: fugiat voluptate mollit
              type: officia veniam
          primary: 'false'
          selected: 'false'
          summary: sit ex exercitation aliqua
          summaryOverride: aute exercitation
          timeZone: fugiat do ut
        kind: calendar#calendarList
        nextPageToken: sit ea
        nextSyncToken: labore consectetur proident occaecat
    UsersMeCalendarListPutResponseExample:
      summary: Successful 200 response
      value:
        accessRole: dolore deserunt nisi sunt
        backgroundColor: consequat tempor esse voluptate
        colorId: eiusmod pariatur et
        conferenceProperties:
          allowedConferenceSolutionTypes:
          - culpa elit
          - cillum
        defaultReminders:
        - method: Excepteur
          minutes: 35541699
        - method: in magna culpa consequat
          minutes: 74169785
        deleted: 'false'
        description: nulla
        etag: incididunt elit in
        foregroundColor: labore fugiat
        hidden: 'false'
        id: nulla
        kind: calendar#calendarListEntry
        location: aliqua
        notificationSettings:
          notifications:
          - method: id dolor minim
            type: ut occaecat sit e
          - method: consequat minim nisi consecte
            type: nulla id
        primary: 'false'
        selected: 'false'
        summary: anim Duis culpa quis consequ
        summaryOverride: deserunt elit reprehenderit
        timeZone: minim commodo incididunt reprehenderit sed
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth 2.0 authentication for Google Books API
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/books: Manage your Google Books library
