openapi: 3.2.0
info:
  title: Google Gmail Modify API
  description: The Gmail API is a RESTful API that can be used to access Gmail mailboxes and send mail. For most web applications the Gmail API is the best choice for authorized access to a user's Gmail data and is suitable for various applications.
  version: 1.0.0
servers:
- url: https://gmail.googleapis.com
  description: Google Gmail API Server
security:
- oauth2Auth: []
tags:
- name: Modify
  description: Operations related to Modify
paths:
  /gmail/v1/users/{userId}/threads/{id}/modify:
    post:
      tags:
      - Modify
      summary: Google Modify Threads
      description: Modifies the labels applied to the thread. This applies to all messages in the thread.
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      - name: id
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersThreadsModifyPostRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersThreadsModifyPostResponse'
              examples:
                UsersThreadsModifyPostResponseExample:
                  $ref: '#/components/examples/UsersThreadsModifyPostResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersThreadsModifyPostResponseExample
components:
  schemas:
    UsersThreadsModifyPostResponse:
      description: UsersThreadsModifyPostResponse schema
      type: object
      properties:
        id:
          type: string
        snippet:
          type: string
        historyId:
          type: string
        messages:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              threadId:
                type: string
              labelIds:
                type: array
                items:
                  type: string
              snippet:
                type: string
              historyId:
                type: string
              internalDate:
                type: string
              payload:
                type: object
                properties:
                  partId:
                    type: string
                  mimeType:
                    type: string
                  filename:
                    type: string
                  headers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                  body:
                    type: object
                    properties:
                      attachmentId:
                        type: string
                      size:
                        type: integer
                      data:
                        type: string
                  parts:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
              sizeEstimate:
                type: integer
              raw:
                type: string
    UsersThreadsModifyPostRequest:
      description: UsersThreadsModifyPostRequest schema
      type: object
      example:
        addLabelIds:
        - labore anim culpa aliqua
        - Duis sed irure Ut aliqua
        removeLabelIds:
        - consectetur et dolore Lorem
        - reprehenderit tempor id dolore incididunt
  examples:
    UsersThreadsModifyPostResponseExample:
      summary: Successful 200 response
      value:
        id: nostrud deserunt
        snippet: cillum quis
        historyId: id ea ad amet venia
        messages:
        - id: exercitation sint
          threadId: Ut sed occaecat
          labelIds:
          - in commodo
          - sit dolor
          snippet: dolor fugiat Ut
          historyId: Lorem quis ullamco veniam
          internalDate: consectetur elit dolor
          payload:
            partId: mi
            mimeType: elit
            filename: ex
            headers:
            - name: velit do voluptate
              value: in reprehenderit sit pariatur
            - name: enim
              value: vel
            body:
              attachmentId: e
              size: 62147464
              data: aliquip aute in Excepteur
            parts:
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
          sizeEstimate: -33441686
          raw: Ut sit
        - id: magna pariatur
          threadId: et
          labelIds:
          - est dolore
          - Lorem Duis amet dolore
          snippet: dolore est reprehender
          historyId: in ex veniam nulla
          internalDate: ut
          payload:
            partId: do consectetur tempor qui in
            mimeType: Excepteur in
            filename: reprehenderit
            headers:
            - name: nulla sed ut
              value: et occaecat
            - name: mollit elit commodo nostrud pariatur
              value: aliqua
            body:
              attachmentId: sit sunt occaecat
              size: 23654047
              data: dolor ut
            parts:
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
          sizeEstimate: 2028457
          raw: ipsum enim minim
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
