openapi: 3.2.0
info:
  title: Google Gmail Lists API
  description: The Gmail API is a RESTful API that can be used to access Gmail mailboxes and send mail. For most web applications the Gmail API is the best choice for authorized access to a user's Gmail data and is suitable for various applications.
  version: 1.0.0
servers:
- url: https://gmail.googleapis.com
  description: Google Gmail API Server
security:
- oauth2Auth: []
tags:
- name: Lists
  description: Operations related to Lists
paths:
  /gmail/v1/users/{userId}/messages:
    get:
      tags:
      - Lists
      summary: Google List Messages
      description: Lists the messages in the user's mailbox.
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: maxResults
        in: query
        schema:
          type: string
        example: '{{maxResults}}'
      - name: pageToken
        in: query
        schema:
          type: string
        example: '{{pageToken}}'
      - name: q
        in: query
        schema:
          type: string
        example: '{{q}}'
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: '{{userId}}'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GmailUsersMessagesGetResponse'
              examples:
                GmailUsersMessagesGetResponseExample:
                  $ref: '#/components/examples/GmailUsersMessagesGetResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: GmailUsersMessagesGetResponseExample
  /gmail/v1/users/{userId}/threads:
    get:
      tags:
      - Lists
      summary: Google List Threads
      description: Lists the threads in the user's mailbox.
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: '{{userID}}'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GmailUsersThreadsGetResponse1'
              examples:
                GmailUsersThreadsGetResponse1Example:
                  $ref: '#/components/examples/GmailUsersThreadsGetResponse1Example'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: GmailUsersThreadsGetResponse1Example
  /gmail/v1/users/{userId}/settings/cse/keypairs:
    get:
      tags:
      - Lists
      summary: Google List CSE Keypairs
      description: Lists client-side encryption key pairs for an authenticated user.
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsCseKeypairsGetResponse1'
              examples:
                SettingsCseKeypairsGetResponse1Example:
                  $ref: '#/components/examples/SettingsCseKeypairsGetResponse1Example'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SettingsCseKeypairsGetResponse1Example
  /gmail/v1/users/{userId}/settings/cse/identities:
    get:
      tags:
      - Lists
      summary: Google List CSE Identites
      description: Lists the client-side encrypted identities for an authenticated user.
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsCseIdentitiesGetResponse'
              examples:
                SettingsCseIdentitiesGetResponseExample:
                  $ref: '#/components/examples/SettingsCseIdentitiesGetResponseExample'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SettingsCseIdentitiesGetResponseExample
  /gmail/v1/users/{userId}/settings/filters:
    get:
      tags:
      - Lists
      summary: Google List Filters
      description: Lists the message filters of a Gmail user.
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: userId
        in: path
        schema:
          type: string
        required: true
        description: '(Required) '
        example: incididunt labore i
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersSettingsFiltersGetResponse1'
              examples:
                UsersSettingsFiltersGetResponse1Example:
                  $ref: '#/components/examples/UsersSettingsFiltersGetResponse1Example'
      x-api-evangelist-processing:
        ChooseTags: true
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: UsersSettingsFiltersGetResponse1Example
components:
  schemas:
    SettingsCseKeypairsGetResponse1:
      description: SettingsCseKeypairsGetResponse1 schema
      type: object
      properties:
        cseKeyPairs:
          type: array
          items:
            type: object
            properties:
              keyPairId:
                type: string
              pkcs7:
                type: string
              pem:
                type: string
              subjectEmailAddresses:
                type: array
                items:
                  type: string
              enablementState:
                type: string
              disableTime:
                type: string
              privateKeyMetadata:
                type: array
                items:
                  type: object
                  properties:
                    privateKeyMetadataId:
                      type: string
                    kaclsKeyMetadata:
                      type: object
                      properties:
                        kaclsUri:
                          type: string
                        kaclsData:
                          type: string
                    hardwareKeyMetadata:
                      type: object
                      properties:
                        description:
                          type: string
        nextPageToken:
          type: string
    GmailUsersMessagesGetResponse:
      description: GmailUsersMessagesGetResponse schema
      type: object
      properties:
        messages:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              threadId:
                type: string
              labelIds:
                type: array
                items:
                  type: string
              snippet:
                type: string
              historyId:
                type: string
              internalDate:
                type: string
              payload:
                type: object
                properties:
                  partId:
                    type: string
                  mimeType:
                    type: string
                  filename:
                    type: string
                  headers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                  body:
                    type: object
                    properties:
                      attachmentId:
                        type: string
                      size:
                        type: integer
                      data:
                        type: string
                  parts:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
              sizeEstimate:
                type: integer
              raw:
                type: string
        nextPageToken:
          type: string
        resultSizeEstimate:
          type: integer
    UsersSettingsFiltersGetResponse1:
      description: UsersSettingsFiltersGetResponse1 schema
      type: object
      properties:
        filter:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              criteria:
                type: object
                properties:
                  from:
                    type: string
                  to:
                    type: string
                  subject:
                    type: string
                  query:
                    type: string
                  negatedQuery:
                    type: string
                  hasAttachment:
                    type: boolean
                  excludeChats:
                    type: boolean
                  size:
                    type: integer
                  sizeComparison:
                    type: string
              action:
                type: object
                properties:
                  addLabelIds:
                    type: array
                    items:
                      type: string
                  removeLabelIds:
                    type: array
                    items:
                      type: string
                  forward:
                    type: string
    SettingsCseIdentitiesGetResponse:
      description: SettingsCseIdentitiesGetResponse schema
      type: object
      properties:
        cseIdentities:
          type: array
          items:
            type: object
            properties:
              emailAddress:
                type: string
              primaryKeyPairId:
                type: string
              signAndEncryptKeyPairs:
                type: object
                properties:
                  signingKeyPairId:
                    type: string
                  encryptionKeyPairId:
                    type: string
        nextPageToken:
          type: string
    GmailUsersThreadsGetResponse1:
      description: GmailUsersThreadsGetResponse1 schema
      type: object
      properties:
        threads:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              snippet:
                type: string
              historyId:
                type: string
              messages:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    threadId:
                      type: string
                    labelIds:
                      type: array
                      items:
                        type: string
                    snippet:
                      type: string
                    historyId:
                      type: string
                    internalDate:
                      type: string
                    payload:
                      type: object
                      properties:
                        partId:
                          type: string
                        mimeType:
                          type: string
                        filename:
                          type: string
                        headers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                        body:
                          type: object
                          properties:
                            attachmentId:
                              type: string
                            size:
                              type: integer
                            data:
                              type: string
                        parts:
                          type: array
                          items:
                            type: object
                            properties:
                              value:
                                type: string
                    sizeEstimate:
                      type: integer
                    raw:
                      type: string
        nextPageToken:
          type: string
        resultSizeEstimate:
          type: integer
  examples:
    SettingsCseIdentitiesGetResponseExample:
      summary: Successful 200 response
      value:
        cseIdentities:
        - emailAddress: adipisicing culpa ipsum
          primaryKeyPairId: incididunt pariatur cupidatat in
          signAndEncryptKeyPairs:
            signingKeyPairId: Ut sunt proident consectetur
            encryptionKeyPairId: esse id
        - emailAddress: elit dolore laboris
          primaryKeyPairId: eu Excepteur sint
          signAndEncryptKeyPairs:
            signingKeyPairId: culpa
            encryptionKeyPairId: dolore Excepteur ipsum Lorem
        nextPageToken: eiusmod amet voluptate veniam in
    GmailUsersMessagesGetResponseExample:
      summary: Successful 200 response
      value:
        messages:
        - id: sed proident adipisicing culpa esse
          threadId: ullamco
          labelIds:
          - velit dolor
          - eiusmod veniam eu
          snippet: anim nisi
          historyId: aute
          internalDate: dolore tempor
          payload:
            partId: non sint ea incididunt dolor
            mimeType: enim aliquip Duis
            filename: tempor nostrud laborum
            headers:
            - name: occaecat mollit est
              value: amet
            - name: Ut aliquip ea
              value: deserunt qui
            body:
              attachmentId: 'in laborum dolore '
              size: -13005468
              data: veniam in qui
            parts:
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
          sizeEstimate: -28255502
          raw: culpa
        - id: cupidatat esse magna dolore
          threadId: ea eiusmod
          labelIds:
          - dolore commodo
          - Ut in et irure
          snippet: esse non
          historyId: ex nulla nisi veniam dolor
          internalDate: tempor pr
          payload:
            partId: dolor Excepteur consequat
            mimeType: magna nulla
            filename: non proident
            headers:
            - name: eiusmod nostrud reprehenderit proident
              value: in ad
            - name: consequat cillum
              value: officia mollit e
            body:
              attachmentId: dolore id dolor esse
              size: -9079183
              data: aute L
            parts:
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            - value: '<Circular reference to #/components/schemas/MessagePart detected>'
          sizeEstimate: 11691603
          raw: eiusmod esse
        nextPageToken: ipsum reprehenderit Duis in veniam
        resultSizeEstimate: -35985941
    UsersSettingsFiltersGetResponse1Example:
      summary: Successful 200 response
      value:
        filter:
        - id: 'reprehenderit Duis '
          criteria:
            from: nostrud anim reprehenderit
            to: officia
            subject: magna
            query: sint elit
            negatedQuery: Excepteur quis est
            hasAttachment: true
            excludeChats: false
            size: 73367794
            sizeComparison: unspecified
          action:
            addLabelIds:
            - nisi elit voluptate
            - sunt exercitation
            removeLabelIds:
            - pariatur in laborum veniam
            - irure in
            forward: occaecat Ut veniam
        - id: Ut deserunt
          criteria:
            from: magna non Duis nostrud Ut
            to: ut officia exercitation in
            subject: tempor minim anim ipsum
            query: sit anim
            negatedQuery: voluptate in tempor elit
            hasAttachment: true
            excludeChats: false
            size: 29351468
            sizeComparison: smaller
          action:
            addLabelIds:
            - adipisicing labore dolore
            - dolor
            removeLabelIds:
            - esse cupidatat
            - mollit aliqua
            forward: est occaecat officia
    GmailUsersThreadsGetResponse1Example:
      summary: Successful 200 response
      value:
        threads:
        - id: commodo
          snippet: eiusmod consequat qui non quis
          historyId: sunt dolore
          messages:
          - id: enim
            threadId: dolore quis exercitation
            labelIds:
            - Duis sint dolore
            - in labore ut commodo
            snippet: nostrud dolore consectetur Excepteur
            historyId: ea elit consectet
            internalDate: proident ullamco
            payload:
              partId: consectetur pariatur dolore
              mimeType: ad occaecat culpa ullamco
              filename: officia elit
              headers:
              - name: co
                value: deserunt ut
              - name: do
                value: ea dolor
              body:
                attachmentId: quis elit commodo
                size: 44099715
                data: irure dolore ut
              parts:
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            sizeEstimate: 21887814
            raw: nulla ipsum Ut
          - id: in dolor proident
            threadId: dolore culpa fugiat
            labelIds:
            - in ut amet
            - Ut sit dolor ut
            snippet: nisi Duis deserunt labore
            historyId: sunt pariatur elit laboris ex
            internalDate: esse pariatur
            payload:
              partId: laboris nulla et
              mimeType: dolore ullamco consectetur nostrud
              filename: aliqua commodo
              headers:
              - name: Ut
                value: laborum
              - name: consequat
                value: esse
              body:
                attachmentId: qui consequat minim
                size: 83387838
                data: id
              parts:
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            sizeEstimate: 70145632
            raw: cillum in ipsum ex
        - id: qui ipsum veniam irure fugiat
          snippet: elit occaecat magna
          historyId: mollit
          messages:
          - id: laborum et
            threadId: elit sint quis
            labelIds:
            - sunt amet aute dolore fugiat
            - Ut aliqua
            snippet: do magna
            historyId: aliqua enim labore
            internalDate: laboris tempor anim voluptate
            payload:
              partId: aute Ut nisi eiusmod
              mimeType: non deserunt anim
              filename: magna
              headers:
              - name: est sunt fugiat
                value: deserunt exer
              - name: consectetur anim
                value: laborum elit
              body:
                attachmentId: dolor id esse proident
                size: -31164209
                data: irure consectetur
              parts:
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            sizeEstimate: -76389446
            raw: nulla dolor nisi reprehenderit sint
          - id: ea laborum sint
            threadId: laboris magna
            labelIds:
            - 'velit '
            - ad sint sunt ex n
            snippet: ea in magna ve
            historyId: sit tempor
            internalDate: qui laborum
            payload:
              partId: aute dolore deserunt do veniam
              mimeType: voluptate ut ad irure est
              filename: nostrud Lorem aliquip elit anim
              headers:
              - name: voluptate sed
                value: in ullamco consequat
              - name: ullamco
                value: ex
              body:
                attachmentId: elit eiusmod sint
                size: 93740460
                data: in non nulla anim
              parts:
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
              - value: '<Circular reference to #/components/schemas/MessagePart detected>'
            sizeEstimate: 76344706
            raw: nisi nostrud
        nextPageToken: Exce
        resultSizeEstimate: -82340850
    SettingsCseKeypairsGetResponse1Example:
      summary: Successful 200 response
      value:
        cseKeyPairs:
        - keyPairId: qui in ad ullamco
          pkcs7: Lorem tempor
          pem: ipsum fugiat Excepteu
          subjectEmailAddresses:
          - sunt
          - in ullamco do
          enablementState: enabled
          disableTime: ad qui
          privateKeyMetadata:
          - privateKeyMetadataId: in
            kaclsKeyMetadata:
              kaclsUri: in et sed aute
              kaclsData: laboris Lorem et esse
            hardwareKeyMetadata:
              description: adipisicing Excepteur
          - privateKeyMetadataId: sit ea
            kaclsKeyMetadata:
              kaclsUri: adipisicing id Ut
              kaclsData: minim
            hardwareKeyMetadata:
              description: eu officia tempor
        - keyPairId: proident tempor dolore et id
          pkcs7: deserunt ea eiusmod adipisicing
          pem: ad enim
          subjectEmailAddresses:
          - nulla dolore
          - ea aliqua Excepteur ut sit
          enablementState: enabled
          disableTime: dolor sed qui
          privateKeyMetadata:
          - privateKeyMetadataId: qui exercitation mollit
            kaclsKeyMetadata:
              kaclsUri: dolore dolor consequat veniam
              kaclsData: occaecat consequat
            hardwareKeyMetadata:
              description: aute esse dolor ipsum
          - privateKeyMetadataId: proident incididunt
            kaclsKeyMetadata:
              kaclsUri: elit
              kaclsData: dolor nulla
            hardwareKeyMetadata:
              description: quis culpa
        nextPageToken: eiusmod dolore anim pariatur
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
