openapi: 3.1.0
info:
  title: Google Books About Calendar ACL Rules API
  description: API for retrieving Bookshelf and Volume resources from Google Books
  version: 1.0.0
  contact:
    name: Google Books API
    url: https://developers.google.com/books
servers:
- url: https://www.googleapis.com/books/v1
  description: Google Books API v1
tags:
- name: Calendar ACL Rules
paths:
  /calendars/{calendarId}/acl/{ruleId}:
    get:
      tags:
      - Calendar ACL Rules
      summary: Google Get Access Control Rule
      description: Returns an access control rule.
      operationId: googleGetaccesscontrolrule
      parameters:
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: alt
        in: query
        schema:
          type: string
        description: Data format for the response.
        example: json
      - name: fields
        in: query
        schema:
          type: string
        description: Selector specifying which fields to include in a partial response.
        example: amet in
      - name: key
        in: query
        schema:
          type: string
        description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
        example: amet in
      - name: oauth_token
        in: query
        schema:
          type: string
        description: OAuth 2.0 token for the current user.
        example: amet in
      - name: prettyPrint
        in: query
        schema:
          type: boolean
        description: Returns response with indentations and line breaks.
        example: 'true'
      - name: quotaUser
        in: query
        schema:
          type: string
        description: An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
        example: amet in
      - name: userIp
        in: query
        schema:
          type: string
        description: Deprecated. Please use quotaUser instead.
        example: amet in
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - name: ruleId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarsAclGetResponse'
              examples:
                CalendarsAclGetResponseExample:
                  $ref: '#/components/examples/CalendarsAclGetResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: CalendarsAclGetResponseExample
    put:
      tags:
      - Calendar ACL Rules
      summary: Google Update Access Control Rule
      description: Updates an access control rule.
      operationId: googleUpdateaccesscontrolrule
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: sendNotifications
        in: query
        schema:
          type: boolean
        example: 'true'
      - name: alt
        in: query
        schema:
          type: string
        description: Data format for the response.
        example: json
      - name: fields
        in: query
        schema:
          type: string
        description: Selector specifying which fields to include in a partial response.
        example: amet in
      - name: key
        in: query
        schema:
          type: string
        description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
        example: amet in
      - name: oauth_token
        in: query
        schema:
          type: string
        description: OAuth 2.0 token for the current user.
        example: amet in
      - name: prettyPrint
        in: query
        schema:
          type: boolean
        description: Returns response with indentations and line breaks.
        example: 'true'
      - name: quotaUser
        in: query
        schema:
          type: string
        description: An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
        example: amet in
      - name: userIp
        in: query
        schema:
          type: string
        description: Deprecated. Please use quotaUser instead.
        example: amet in
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - name: ruleId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarsAclPutRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarsAclPutResponse'
              examples:
                CalendarsAclPutResponseExample:
                  $ref: '#/components/examples/CalendarsAclPutResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: CalendarsAclPutResponseExample
    patch:
      tags:
      - Calendar ACL Rules
      summary: Google Patch Access Control Rule
      description: Updates an access control rule. This method supports patch semantics.
      operationId: googlePatchaccesscontrolrule
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: sendNotifications
        in: query
        schema:
          type: boolean
        example: 'true'
      - name: alt
        in: query
        schema:
          type: string
        description: Data format for the response.
        example: json
      - name: fields
        in: query
        schema:
          type: string
        description: Selector specifying which fields to include in a partial response.
        example: amet in
      - name: key
        in: query
        schema:
          type: string
        description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
        example: amet in
      - name: oauth_token
        in: query
        schema:
          type: string
        description: OAuth 2.0 token for the current user.
        example: amet in
      - name: prettyPrint
        in: query
        schema:
          type: boolean
        description: Returns response with indentations and line breaks.
        example: 'true'
      - name: quotaUser
        in: query
        schema:
          type: string
        description: An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
        example: amet in
      - name: userIp
        in: query
        schema:
          type: string
        description: Deprecated. Please use quotaUser instead.
        example: amet in
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - name: ruleId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarsAclPatchRequest'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarsAclPatchResponse'
              examples:
                CalendarsAclPatchResponseExample:
                  $ref: '#/components/examples/CalendarsAclPatchResponseExample'
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: CalendarsAclPatchResponseExample
    delete:
      tags:
      - Calendar ACL Rules
      summary: Google Delete Access Control Rule
      description: Deletes an access control rule.
      operationId: googleDeleteaccesscontrolrule
      parameters:
      - name: alt
        in: query
        schema:
          type: string
        description: Data format for the response.
        example: json
      - name: fields
        in: query
        schema:
          type: string
        description: Selector specifying which fields to include in a partial response.
        example: amet in
      - name: key
        in: query
        schema:
          type: string
        description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
        example: amet in
      - name: oauth_token
        in: query
        schema:
          type: string
        description: OAuth 2.0 token for the current user.
        example: amet in
      - name: prettyPrint
        in: query
        schema:
          type: boolean
        description: Returns response with indentations and line breaks.
        example: 'true'
      - name: quotaUser
        in: query
        schema:
          type: string
        description: An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
        example: amet in
      - name: userIp
        in: query
        schema:
          type: string
        description: Deprecated. Please use quotaUser instead.
        example: amet in
      - name: calendarId
        in: path
        schema:
          type: string
        required: true
      - name: ruleId
        in: path
        schema:
          type: string
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
      responses:
        '204':
          description: No Content
          headers:
            Content-Type:
              schema:
                type: string
                example: text/plain
          content:
            text/plain:
              schema:
                type: string
      x-microcks-operation:
        delay: 100
        dispatcher: FALLBACK
        dispatcherRules: SuccessExample
components:
  schemas:
    CalendarsAclPatchRequest:
      description: CalendarsAclPatchRequest schema
      type: object
      example:
        etag: velit eu voluptate
        id: ex dolore in sint
        kind: calendar#aclRule
        role: et
        scope:
          type: sit eiusmod culpa do
          value: quis esse
    CalendarsAclPatchResponseScope:
      description: CalendarsAclPatchResponseScope schema
      type: object
      properties:
        type:
          type: string
        value:
          type: string
    CalendarsAclPutResponseScope:
      description: CalendarsAclPutResponseScope schema
      type: object
      properties:
        type:
          type: string
        value:
          type: string
    CalendarsAclPatchResponse:
      description: CalendarsAclPatchResponse schema
      type: object
      properties:
        etag:
          type: string
        id:
          type: string
        kind:
          type: string
        role:
          type: string
        scope:
          $ref: '#/components/schemas/CalendarsAclPatchResponseScope'
    CalendarsAclGetResponseScope:
      description: CalendarsAclGetResponseScope schema
      type: object
      properties:
        type:
          type: string
        value:
          type: string
    CalendarsAclPutResponse:
      description: CalendarsAclPutResponse schema
      type: object
      properties:
        etag:
          type: string
        id:
          type: string
        kind:
          type: string
        role:
          type: string
        scope:
          $ref: '#/components/schemas/CalendarsAclPutResponseScope'
    CalendarsAclPutRequest:
      description: CalendarsAclPutRequest schema
      type: object
      example:
        etag: velit eu voluptate
        id: ex dolore in sint
        kind: calendar#aclRule
        role: et
        scope:
          type: sit eiusmod culpa do
          value: quis esse
    CalendarsAclGetResponse:
      description: CalendarsAclGetResponse schema
      type: object
      properties:
        etag:
          type: string
        id:
          type: string
        kind:
          type: string
        role:
          type: string
        scope:
          $ref: '#/components/schemas/CalendarsAclGetResponseScope'
  examples:
    CalendarsAclPutResponseExample:
      summary: Successful 200 response
      value:
        etag: velit eu voluptate
        id: ex dolore in sint
        kind: calendar#aclRule
        role: et
        scope:
          type: sit eiusmod culpa do
          value: quis esse
    CalendarsAclGetResponseExample:
      summary: Successful 200 response
      value:
        etag: velit eu voluptate
        id: ex dolore in sint
        kind: calendar#aclRule
        role: et
        scope:
          type: sit eiusmod culpa do
          value: quis esse
    CalendarsAclPatchResponseExample:
      summary: Successful 200 response
      value:
        etag: velit eu voluptate
        id: ex dolore in sint
        kind: calendar#aclRule
        role: et
        scope:
          type: sit eiusmod culpa do
          value: quis esse
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth 2.0 authentication for Google Books API
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/books: Manage your Google Books library
